export const AS_NZS_3000_TOC = [
  // SECTION 1
  { section: "1", title: "SCOPE, APPLICATION AND FUNDAMENTAL PRINCIPLES", page: 33, level: 1 },
  { section: "1.1", title: "SCOPE", page: 33, level: 2 },
  { section: "1.2", title: "APPLICATION", page: 33, level: 2 },
  { section: "1.3", title: "REFERENCED DOCUMENTS", page: 34, level: 2 },
  { section: "1.4", title: "DEFINITIONS", page: 34, level: 2 },
  { section: "1.5", title: "FUNDAMENTAL PRINCIPLES", page: 54, level: 2 },
  { section: "1.5.1", title: "Protection against dangers and damage", page: 54, level: 3 },
  { section: "1.5.2", title: "Control and isolation", page: 55, level: 3 },
  { section: "1.5.3", title: "Protection against electric shock", page: 55, level: 3 },
  { section: "1.5.4", title: "Basic protection", page: 56, level: 3 },
  { section: "1.5.5", title: "Fault protection", page: 59, level: 3 },
  { section: "1.5.6", title: "Additional protection by the use of RCDs", page: 62, level: 3 },
  { section: "1.5.7", title: "Basic and fault protection by use of extra-low voltage", page: 63, level: 3 },
  { section: "1.5.8", title: "Protection against thermal effects in normal service", page: 63, level: 3 },
  { section: "1.5.9", title: "Protection against overcurrent", page: 64, level: 3 },
  { section: "1.5.10", title: "Protection against earth fault currents", page: 64, level: 3 },
  { section: "1.5.11", title: "Protection against abnormal voltages", page: 64, level: 3 },
  { section: "1.5.12", title: "Protection against the spread of fire", page: 66, level: 3 },
  { section: "1.5.13", title: "Protection against injury from mechanical movement", page: 66, level: 3 },
  { section: "1.5.14", title: "Protection against external influences", page: 66, level: 3 },
  { section: "1.6", title: "DESIGN OF AN ELECTRICAL INSTALLATION", page: 67, level: 2 },
  { section: "1.6.1", title: "General", page: 67, level: 3 },
  { section: "1.6.2", title: "Supply characteristics", page: 67, level: 3 },
  { section: "1.6.3", title: "Maximum demand", page: 67, level: 3 },
  { section: "1.6.4", title: "Utilization voltage", page: 68, level: 3 },
  { section: "1.6.5", title: "Electrical installation circuit arrangement", page: 68, level: 3 },
  { section: "1.7", title: "SELECTION AND INSTALLATION OF ELECTRICAL EQUIPMENT", page: 68, level: 2 },
  { section: "1.7.1", title: "General", page: 68, level: 3 },
  { section: "1.7.2", title: "Installation work practice", page: 68, level: 3 },
  { section: "1.7.3", title: "Equipment selection", page: 69, level: 3 },
  { section: "1.7.4", title: "Damp situations", page: 70, level: 3 },
  { section: "1.8", title: "VERIFICATION (INSPECTION AND TESTING)", page: 70, level: 2 },
  { section: "1.9", title: "MEANS OF COMPLIANCE", page: 71, level: 2 },
  { section: "1.9.1", title: "Compliance with Part 2 of this Standard", page: 71, level: 3 },
  { section: "1.9.2", title: "Compliance with the requirements of other standards", page: 71, level: 3 },
  { section: "1.9.3", title: "Alterations and repairs", page: 71, level: 3 },
  { section: "1.9.4", title: "Compliance by specific design and installation", page: 71, level: 3 },

  // SECTION 2
  { section: "2", title: "GENERAL ARRANGEMENT, CONTROL AND PROTECTION", page: 75, level: 1 },
  { section: "2.1", title: "GENERAL", page: 75, level: 2 },
  { section: "2.1.1", title: "Application", page: 75, level: 3 },
  { section: "2.1.2", title: "Selection and installation", page: 75, level: 3 },
  { section: "2.2", title: "ARRANGEMENT OF ELECTRICAL INSTALLATION", page: 75, level: 2 },
  { section: "2.2.1", title: "Circuits", page: 75, level: 3 },
  { section: "2.2.2", title: "Maximum demand", page: 77, level: 3 },
  { section: "2.2.3", title: "Selection and installation of conductors", page: 78, level: 3 },
  { section: "2.2.4", title: "Operating characteristics of equipment", page: 78, level: 3 },
  { section: "2.3", title: "CONTROL OF ELECTRICAL INSTALLATION", page: 79, level: 2 },
  { section: "2.3.1", title: "General", page: 79, level: 3 },
  { section: "2.3.2", title: "Common control requirements", page: 80, level: 3 },
  { section: "2.3.3", title: "Main switches", page: 83, level: 3 },
  { section: "2.3.4", title: "Additional isolating switches", page: 86, level: 3 },
  { section: "2.3.5", title: "Emergency switching including emergency stopping", page: 88, level: 3 },
  { section: "2.3.6", title: "Shutting down for mechanical maintenance", page: 90, level: 3 },
  { section: "2.3.7", title: "Functional (control) switching", page: 91, level: 3 },
  { section: "2.4", title: "FAULT PROTECTION", page: 92, level: 2 },
  { section: "2.4.1", title: "General", page: 92, level: 3 },
  { section: "2.4.2", title: "Protection by automatic disconnection of supply", page: 92, level: 3 },
  { section: "2.4.3", title: "Types of devices", page: 93, level: 3 },
  { section: "2.4.4", title: "Auto-reclose devices", page: 93, level: 3 },
  { section: "2.5", title: "PROTECTION AGAINST OVERCURRENT", page: 93, level: 2 },
  { section: "2.5.1", title: "General", page: 93, level: 3 },
  { section: "2.5.2", title: "Devices for protection against both overload and short-circuit currents", page: 96, level: 3 },
  { section: "2.5.3", title: "Protection against overload current", page: 97, level: 3 },
  { section: "2.5.4", title: "Protection against short-circuit current", page: 99, level: 3 },
  { section: "2.5.5", title: "Protection against switchboard internal arcing fault currents", page: 108, level: 3 },
  { section: "2.5.6", title: "Coordination of overload and short-circuit protective devices", page: 111, level: 3 },
  { section: "2.5.7", title: "Reliability of supply", page: 112, level: 3 },
  { section: "2.6", title: "ADDITIONAL PROTECTION BY RESIDUAL CURRENT DEVICES", page: 119, level: 2 },
  { section: "2.6.1", title: "General", page: 119, level: 3 },
  { section: "2.6.2", title: "Selection and arrangement of devices", page: 120, level: 3 },
  { section: "2.6.3", title: "Additional protection by residual current devices", page: 123, level: 3 },
  { section: "2.7", title: "PROTECTION AGAINST OVERVOLTAGE", page: 131, level: 2 },
  { section: "2.7.1", title: "General", page: 131, level: 3 },
  { section: "2.7.2", title: "Protection by insulation or separation", page: 131, level: 3 },
  { section: "2.7.3", title: "Protection by protective devices", page: 132, level: 3 },
  { section: "2.8", title: "PROTECTION AGAINST UNDERVOLTAGE", page: 132, level: 2 },
  { section: "2.8.1", title: "General", page: 132, level: 3 },
  { section: "2.8.2", title: "Selection of protective device", page: 133, level: 3 },
  { section: "2.9", title: "PROTECTION AGAINST FIRE HAZARD DUE TO ARCING FAULTS", page: 133, level: 2 },
  { section: "2.9.1", title: "General", page: 133, level: 3 },
  { section: "2.9.2", title: "Type", page: 133, level: 3 },
  { section: "2.9.3", title: "Rating", page: 134, level: 3 },
  { section: "2.9.4", title: "Arrangement", page: 134, level: 3 },
  { section: "2.9.5", title: "Alterations", page: 134, level: 3 },
  { section: "2.9.6", title: "Final subcircuits in Australia", page: 134, level: 3 },
  { section: "2.9.7", title: "Final subcircuits in New Zealand", page: 134, level: 3 },
  { section: "2.10", title: "SWITCHBOARDS", page: 134, level: 2 },
  { section: "2.10.1", title: "General", page: 134, level: 3 },
  { section: "2.10.2", title: "Location of switchboards", page: 135, level: 3 },
  { section: "2.10.3", title: "Construction", page: 143, level: 3 },
  { section: "2.10.4", title: "Bars", page: 145, level: 3 },
  { section: "2.10.5", title: "Equipment identification", page: 147, level: 3 },
  { section: "2.10.6", title: "Wiring", page: 148, level: 3 },
  { section: "2.10.7", title: "Fire-protective measures", page: 148, level: 3 },

  // SECTION 3
  { section: "3", title: "SELECTION AND INSTALLATION OF WIRING SYSTEMS", page: 150, level: 1 },
  { section: "3.1", title: "GENERAL", page: 150, level: 2 },
  { section: "3.1.1", title: "Application", page: 150, level: 3 },
  { section: "3.1.2", title: "Selection and installation", page: 150, level: 3 },
  { section: "3.2", title: "TYPES OF WIRING SYSTEMS", page: 150, level: 2 },
  { section: "3.3", title: "EXTERNAL INFLUENCES", page: 151, level: 2 },
  { section: "3.3.1", title: "General", page: 151, level: 3 },
  { section: "3.3.2", title: "Particular influences", page: 151, level: 3 },
  { section: "3.4", title: "CURRENT-CARRYING CAPACITY", page: 156, level: 2 },
  { section: "3.4.1", title: "General", page: 156, level: 3 },
  { section: "3.4.2", title: "Operating temperature limits", page: 157, level: 3 },
  { section: "3.4.3", title: "Conductors in parallel", page: 159, level: 3 },
  { section: "3.4.4", title: "Coordination between conductors and protective devices", page: 160, level: 3 },
  { section: "3.5", title: "CONDUCTOR SIZE", page: 160, level: 2 },
  { section: "3.5.1", title: "General", page: 160, level: 3 },
  { section: "3.5.2", title: "Neutral conductor", page: 161, level: 3 },
  { section: "3.5.3", title: "Earthing conductor", page: 163, level: 3 },
  { section: "3.6", title: "VOLTAGE DROP", page: 163, level: 2 },
  { section: "3.6.1", title: "General", page: 163, level: 3 },
  { section: "3.6.2", title: "Value", page: 163, level: 3 },
  { section: "3.6.3", title: "Conductors in parallel", page: 164, level: 3 },
  { section: "3.7", title: "ELECTRICAL CONNECTIONS", page: 164, level: 2 },
  { section: "3.7.1", title: "General", page: 164, level: 3 },
  { section: "3.7.2", title: "Connection methods", page: 164, level: 3 },
  { section: "3.7.3", title: "Joints in cables", page: 168, level: 3 },
  { section: "3.7.4", title: "Installation couplers", page: 168, level: 3 },
  { section: "3.8", title: "IDENTIFICATION", page: 168, level: 2 },
  { section: "3.8.1", title: "General", page: 168, level: 3 },
  { section: "3.8.2", title: "Colour identification", page: 169, level: 3 },
  { section: "3.8.3", title: "Exceptions and special applications", page: 170, level: 3 },
  { section: "3.9", title: "INSTALLATION REQUIREMENTS", page: 172, level: 2 },
  { section: "3.9.1", title: "General", page: 172, level: 3 },
  { section: "3.9.2", title: "Methods of installation", page: 173, level: 3 },
  { section: "3.9.3", title: "Support and fixing", page: 173, level: 3 },
  { section: "3.9.4", title: "Protection against mechanical damage", page: 174, level: 3 },
  { section: "3.9.5", title: "Wiring systems installed vertically", page: 178, level: 3 },
  { section: "3.9.6", title: "Change of direction", page: 178, level: 3 },
  { section: "3.9.7", title: "Particular installation requirements", page: 178, level: 3 },
  { section: "3.9.8", title: "Prevention of mutual detrimental effects between services", page: 182, level: 3 },
  { section: "3.9.9", title: "Selection and installation to minimize the spread of fire", page: 185, level: 3 },
  { section: "3.9.10", title: "Limitation of circulating and eddy currents", page: 188, level: 3 },
  { section: "3.9.11", title: "Minimization of electromagnetic interference", page: 189, level: 3 },
  { section: "3.10", title: "ENCLOSURE OF CABLES", page: 190, level: 2 },
  { section: "3.10.1", title: "General", page: 190, level: 3 },
  { section: "3.10.2", title: "Wiring enclosures", page: 190, level: 3 },
  { section: "3.10.3", title: "Installation of wiring enclosures", page: 191, level: 3 },
  { section: "3.11", title: "UNDERGROUND WIRING SYSTEMS", page: 193, level: 2 },
  { section: "3.11.1", title: "Suitability and protection", page: 193, level: 3 },
  { section: "3.11.2", title: "Classification of wiring systems", page: 193, level: 3 },
  { section: "3.11.3", title: "Arrangements", page: 194, level: 3 },
  { section: "3.11.4", title: "Installation requirements", page: 197, level: 3 },
  { section: "3.11.5", title: "Spacing from other underground services", page: 203, level: 3 },
  { section: "3.12", title: "AERIAL WIRING SYSTEMS", page: 203, level: 2 },
  { section: "3.12.1", title: "Types of conductor", page: 203, level: 3 },
  { section: "3.12.2", title: "Arrangements", page: 204, level: 3 },
  { section: "3.12.3", title: "Clearances", page: 205, level: 3 },
  { section: "3.12.4", title: "Distance between supports (spans)", page: 207, level: 3 },
  { section: "3.12.5", title: "Aerial conductor supports", page: 207, level: 3 },
  { section: "3.12.6", title: "Poles and posts (including supports, struts and extensions to structures)", page: 208, level: 3 },
  { section: "3.12.7", title: "Joints and connections", page: 209, level: 3 },
  { section: "3.13", title: "CABLES SUPPORTED BY A CATENARY", page: 209, level: 2 },
  { section: "3.13.1", title: "Types of cables", page: 209, level: 3 },
  { section: "3.13.2", title: "Catenary supports", page: 209, level: 3 },
  { section: "3.13.3", title: "Clearances", page: 209, level: 3 },
  { section: "3.14", title: "SAFETY SERVICES", page: 209, level: 2 },
  { section: "3.15", title: "BUSWAYS, INCLUDING RISING MAINS SYSTEMS", page: 211, level: 2 },
  { section: "3.16", title: "EARTH SHEATH RETURN (ESR) SYSTEM", page: 211, level: 2 },

  // SECTION 4
  { section: "4", title: "SELECTION AND INSTALLATION OF ELECTRICAL EQUIPMENT", page: 212, level: 1 },
  { section: "4.1", title: "GENERAL", page: 212, level: 2 },
  { section: "4.1.1", title: "Application", page: 212, level: 3 },
  { section: "4.1.2", title: "Selection and installation", page: 212, level: 3 },
  { section: "4.1.3", title: "External influences", page: 213, level: 3 },
  { section: "4.1.4", title: "Adverse effects and interference", page: 215, level: 3 },
  { section: "4.1.5", title: "Air extraction systems", page: 216, level: 3 },
  { section: "4.2", title: "PROTECTION AGAINST THERMAL EFFECTS", page: 216, level: 2 },
  { section: "4.2.1", title: "General", page: 216, level: 3 },
  { section: "4.2.2", title: "Prevention of fire hazard", page: 216, level: 3 },
  { section: "4.2.3", title: "Protection against burns", page: 218, level: 3 },
  { section: "4.3", title: "CONNECTION OF ELECTRICAL EQUIPMENT", page: 219, level: 2 },
  { section: "4.3.1", title: "General", page: 219, level: 3 },
  { section: "4.3.2", title: "Direct connection", page: 219, level: 3 },
  { section: "4.3.3", title: "Installation wiring connected by an installation coupler(s)", page: 220, level: 3 },
  { section: "4.3.4", title: "Socket-outlets in installation wiring", page: 221, level: 3 },
  { section: "4.3.5", title: "Other connecting devices", page: 221, level: 3 },
  { section: "4.3.6", title: "Equipment wiring", page: 222, level: 3 },
  { section: "4.4", title: "SOCKET-OUTLETS", page: 223, level: 2 },
  { section: "4.4.1", title: "Types", page: 223, level: 3 },
  { section: "4.4.2", title: "Location", page: 225, level: 3 },
  { section: "4.4.3", title: "Earthing contacts", page: 226, level: 3 },
  { section: "4.4.4", title: "Switching device", page: 226, level: 3 },
  { section: "4.4.5", title: "Polarization and phase sequence", page: 228, level: 3 },
  { section: "4.5", title: "LIGHTING EQUIPMENT AND ACCESSORIES", page: 228, level: 2 },
  { section: "4.5.1", title: "Lampholders, including lampholders incorporated in a luminaire", page: 228, level: 3 },
  { section: "4.5.2", title: "Lamps and luminaires", page: 229, level: 3 },
  { section: "4.6", title: "SMOKE ALARMS", page: 243, level: 2 },
  { section: "4.7", title: "COOKING APPLIANCES", page: 243, level: 2 },
  { section: "4.7.1", title: "Switching device", page: 243, level: 3 },
  { section: "4.7.2", title: "Connection—New Zealand only", page: 244, level: 3 },
  { section: "4.7.3", title: "Clearance from open cooking surfaces", page: 244, level: 3 },
  { section: "4.8", title: "APPLIANCES PRODUCING HOT WATER OR STEAM", page: 245, level: 2 },
  { section: "4.8.1", title: "General", page: 245, level: 3 },
  { section: "4.8.2", title: "Water heaters", page: 246, level: 3 },
  { section: "4.9", title: "ROOM HEATERS", page: 246, level: 2 },
  { section: "4.9.1", title: "General", page: 246, level: 3 },
  { section: "4.9.2", title: "Isolating switches", page: 247, level: 3 },
  { section: "4.9.3", title: "Functional switches", page: 247, level: 3 },
  { section: "4.10", title: "ELECTRIC HEATING CABLES FOR FLOORS AND CEILINGS AND TRACE HEATING APPLICATIONS", page: 247, level: 2 },
  { section: "4.10.1", title: "General", page: 247, level: 3 },
  { section: "4.10.2", title: "Heating cables", page: 247, level: 3 },
  { section: "4.10.3", title: "Isolating switches", page: 248, level: 3 },
  { section: "4.10.4", title: "Functional switches", page: 248, level: 3 },
  { section: "4.10.5", title: "Additional protection", page: 248, level: 3 },
  { section: "4.10.6", title: "Signs", page: 249, level: 3 },
  { section: "4.11", title: "ELECTRIC DUCT HEATERS", page: 249, level: 2 },
  { section: "4.12", title: "ELECTRICITY CONVERTERS", page: 249, level: 2 },
  { section: "4.12.1", title: "General", page: 249, level: 3 },
  { section: "4.12.2", title: "Selection and installation", page: 250, level: 3 },
  { section: "4.12.3", title: "Control", page: 250, level: 3 },
  { section: "4.12.4", title: "Isolation", page: 250, level: 3 },
  { section: "4.12.5", title: "Overcurrent protection", page: 251, level: 3 },
  { section: "4.12.6", title: "Earthing", page: 252, level: 3 },
  { section: "4.12.7", title: "Neutral continuity", page: 252, level: 3 },
  { section: "4.12.8", title: "Electrical equipment connected to output", page: 252, level: 3 },
  { section: "4.13", title: "MOTORS", page: 253, level: 2 },
  { section: "4.13.1", title: "Protection against injury from mechanical movement", page: 253, level: 3 },
  { section: "4.13.2", title: "Protection against overload", page: 254, level: 3 },
  { section: "4.13.3", title: "Protection against overtemperature", page: 255, level: 3 },
  { section: "4.14", title: "TRANSFORMERS", page: 256, level: 2 },
  { section: "4.14.1", title: "General", page: 256, level: 3 },
  { section: "4.14.2", title: "Secondary circuit", page: 256, level: 3 },
  { section: "4.14.3", title: "Low voltage transformer supply", page: 257, level: 3 },
  { section: "4.14.4", title: "Autotransformers", page: 257, level: 3 },
  { section: "4.14.5", title: "Step-up transformers", page: 257, level: 3 },
  { section: "4.15", title: "CAPACITORS", page: 257, level: 2 },
  { section: "4.15.1", title: "General", page: 257, level: 3 },
  { section: "4.15.2", title: "Electrical equipment", page: 257, level: 3 },
  { section: "4.15.3", title: "Provision for discharge and control", page: 258, level: 3 },
  { section: "4.16", title: "ELECTRICAL EQUIPMENT CONTAINING LIQUID DIELECTRICS", page: 260, level: 2 },
  { section: "4.16.1", title: "General", page: 260, level: 3 },
  { section: "4.16.2", title: "Liquid dielectrics having a flashpoint not exceeding 250°C", page: 260, level: 3 },
  { section: "4.17", title: "BATTERIES", page: 260, level: 2 },
  { section: "4.18", title: "GAS APPLIANCES AND EQUIPMENT", page: 260, level: 2 },
  { section: "4.18.1", title: "Gas appliances", page: 260, level: 3 },
  { section: "4.18.2", title: "Gas cylinders containing heavier-than-air gases—Outdoors", page: 261, level: 3 },
  { section: "4.18.3", title: "Gas cylinders—Indoors—New Zealand only", page: 262, level: 3 },
  { section: "4.18.4", title: "Gas relief vent terminal—Natural gas, LP Gas or Biogas", page: 262, level: 3 },
  { section: "4.18.5", title: "Reticulated lighter-than-air gas system, metering system and regulators—New Zealand only", page: 263, level: 3 },
  { section: "4.19", title: "AIRCONDITIONING AND HEAT PUMP SYSTEMS", page: 264, level: 2 },
  { section: "4.20", title: "LIFTS", page: 265, level: 2 },
  { section: "4.20.1", title: "General", page: 265, level: 3 },
  { section: "4.20.2", title: "Lift supply arrangement", page: 265, level: 3 },
  { section: "4.20.3", title: "Labelling", page: 265, level: 3 },
  { section: "4.20.4", title: "Motor-room-less lifts (MRLs)", page: 265, level: 3 },

  // SECTION 5
  { section: "5", title: "EARTHING ARRANGEMENTS AND EARTHING CONDUCTORS", page: 267, level: 1 },
  { section: "5.1", title: "GENERAL", page: 267, level: 2 },
  { section: "5.1.1", title: "Application", page: 267, level: 3 },
  { section: "5.1.2", title: "Selection and installation", page: 267, level: 3 },
  { section: "5.1.3", title: "MEN earthing system", page: 267, level: 3 },
  { section: "5.1.4", title: "Other earthing systems", page: 270, level: 3 },
  { section: "5.2", title: "EARTHING FUNCTIONS", page: 271, level: 2 },
  { section: "5.2.1", title: "Protective earthing", page: 271, level: 3 },
  { section: "5.2.2", title: "Functional earthing (FE)", page: 271, level: 3 },
  { section: "5.2.3", title: "Earthing for combined protective and functional purposes", page: 272, level: 3 },
  { section: "5.3", title: "EARTHING SYSTEM PARTS", page: 272, level: 2 },
  { section: "5.3.1", title: "General", page: 272, level: 3 },
  { section: "5.3.2", title: "Earthing conductor material and type", page: 273, level: 3 },
  { section: "5.3.3", title: "Earthing conductor size (cross-sectional area)", page: 276, level: 3 },
  { section: "5.3.4", title: "Main earthing terminal/connection or bar", page: 280, level: 3 },
  { section: "5.3.5", title: "MEN connection", page: 281, level: 3 },
  { section: "5.3.6", title: "Earth electrodes", page: 282, level: 3 },
  { section: "5.3.7", title: "Functional earthing conductors", page: 284, level: 3 },
  { section: "5.4", title: "EARTHING OF EQUIPMENT", page: 284, level: 2 },
  { section: "5.4.1", title: "General", page: 284, level: 3 },
  { section: "5.4.2", title: "Socket-outlets", page: 286, level: 3 },
  { section: "5.4.3", title: "Lighting points", page: 286, level: 3 },
  { section: "5.4.4", title: "Luminaires", page: 286, level: 3 },
  { section: "5.4.5", title: "Conductive supports for aerial conductors", page: 287, level: 3 },
  { section: "5.4.6", title: "Structural metalwork including conductive building materials", page: 287, level: 3 },
  { section: "5.4.7", title: "Submersible pumps", page: 288, level: 3 },
  { section: "5.4.8", title: "Variable frequency devices", page: 288, level: 3 },
  { section: "5.5", title: "EARTHING ARRANGEMENTS", page: 289, level: 2 },
  { section: "5.5.1", title: "Main earthing conductor", page: 289, level: 3 },
  { section: "5.5.2", title: "Protective earthing conductors", page: 290, level: 3 },
  { section: "5.5.3", title: "Particular methods of earthing", page: 292, level: 3 },
  { section: "5.5.4", title: "Continuity", page: 300, level: 3 },
  { section: "5.5.5", title: "Installation", page: 301, level: 3 },
  { section: "5.5.6", title: "Connections", page: 302, level: 3 },
  { section: "5.6", title: "EQUIPOTENTIAL BONDING", page: 303, level: 2 },
  { section: "5.6.1", title: "General", page: 303, level: 3 },
  { section: "5.6.2", title: "Arrangement", page: 304, level: 3 },
  { section: "5.6.3", title: "Bonding conductors", page: 311, level: 3 },
  { section: "5.7", title: "EARTH FAULT-LOOP IMPEDANCE", page: 312, level: 2 },
  { section: "5.7.1", title: "General", page: 312, level: 3 },
  { section: "5.7.2", title: "Disconnection times", page: 313, level: 3 },
  { section: "5.7.3", title: "Earth fault-loop", page: 313, level: 3 },
  { section: "5.7.4", title: "Impedance", page: 314, level: 3 },
  { section: "5.7.5", title: "Supplementary equipotential bonding", page: 314, level: 3 },
  { section: "5.8", title: "OTHER EARTHING ARRANGEMENTS", page: 315, level: 2 },

  // SECTION 6 - CRITICAL FOR ELECTRICIANS
  { section: "6", title: "DAMP SITUATIONS", page: 316, level: 1 },
  { section: "6.1", title: "GENERAL", page: 316, level: 2 },
  { section: "6.1.1", title: "Application", page: 316, level: 3 },
  { section: "6.1.2", title: "Selection and installation", page: 316, level: 3 },
  { section: "6.2", title: "BATHS, SHOWERS AND OTHER FIXED WATER CONTAINERS", page: 317, level: 2 },
  { section: "6.2.1", title: "Scope", page: 317, level: 3 },
  { section: "6.2.2", title: "Classification of zones", page: 317, level: 3 },
  { section: "6.2.3", title: "Protection against electric shock—Prohibited measures", page: 320, level: 3 },
  { section: "6.2.4", title: "Selection and installation of electrical equipment", page: 320, level: 3 },
  { section: "6.3", title: "SWIMMING POOLS, PADDLING POOLS AND SPA POOLS OR TUBS", page: 336, level: 2 },
  { section: "6.3.1", title: "Scope", page: 336, level: 3 },
  { section: "6.3.2", title: "Classification of zones", page: 337, level: 3 },
  { section: "6.3.3", title: "Protection against electric shock", page: 338, level: 3 },
  { section: "6.3.4", title: "Selection and installation of electrical equipment", page: 339, level: 3 },
  { section: "6.4", title: "FOUNTAINS AND WATER FEATURES", page: 348, level: 2 },
  { section: "6.4.1", title: "Scope", page: 348, level: 3 },
  { section: "6.4.2", title: "Classification of zones", page: 349, level: 3 },
  { section: "6.4.3", title: "Protection against electric shock", page: 349, level: 3 },
  { section: "6.4.4", title: "Selection and installation of electrical equipment", page: 350, level: 3 },
  { section: "6.5", title: "SAUNAS", page: 354, level: 2 },
  { section: "6.5.1", title: "Scope", page: 354, level: 3 },
  { section: "6.5.2", title: "Classification of zones", page: 354, level: 3 },
  { section: "6.5.3", title: "Protection against electric shock", page: 355, level: 3 },
  { section: "6.5.4", title: "Selection and installation of electrical equipment", page: 355, level: 3 },
  { section: "6.6", title: "REFRIGERATION ROOMS", page: 358, level: 2 },
  { section: "6.6.1", title: "Scope", page: 358, level: 3 },
  { section: "6.6.2", title: "Protection against electric shock", page: 358, level: 3 },
  { section: "6.6.3", title: "Selection and installation of electrical equipment", page: 358, level: 3 },
  { section: "6.7", title: "SANITIZATION AND GENERAL HOSING-DOWN OPERATIONS", page: 360, level: 2 },
  { section: "6.7.1", title: "Scope", page: 360, level: 3 },
  { section: "6.7.2", title: "Classification of zone", page: 360, level: 3 },
  { section: "6.7.3", title: "Protection against electric shock", page: 361, level: 3 },
  { section: "6.7.4", title: "Selection and installation of electrical equipment", page: 361, level: 3 },

  // SECTION 7
  { section: "7", title: "SPECIAL ELECTRICAL INSTALLATIONS", page: 362, level: 1 },
  { section: "7.1", title: "GENERAL", page: 362, level: 2 },
  { section: "7.1.1", title: "Application", page: 362, level: 3 },
  { section: "7.1.2", title: "Selection and installation", page: 362, level: 3 },
  { section: "7.2", title: "SAFETY SERVICES", page: 363, level: 2 },
  { section: "7.2.1", title: "Scope and general", page: 363, level: 3 },
  { section: "7.2.2", title: "Supply systems", page: 364, level: 3 },
  { section: "7.2.3", title: "Main switchboard and switchgear", page: 367, level: 3 },
  { section: "7.2.4", title: "Main switches", page: 371, level: 3 },
  { section: "7.2.5", title: "Fire pumps and fire pump control equipment", page: 373, level: 3 },
  { section: "7.2.6", title: "Fire and smoke detection equipment and fire alarm systems", page: 377, level: 3 },
  { section: "7.2.7", title: "Air-handling systems", page: 378, level: 3 },
  { section: "7.2.8", title: "Evacuation equipment", page: 379, level: 3 },
  { section: "7.2.9", title: "Emergency lifts", page: 380, level: 3 },
  { section: "7.2.10", title: "Emergency motor-room-less lifts", page: 382, level: 3 },
  { section: "7.3", title: "ELECTRICITY GENERATION SYSTEMS", page: 384, level: 2 },
  { section: "7.3.1", title: "General", page: 384, level: 3 },
  { section: "7.3.2", title: "Selection and installation of system", page: 385, level: 3 },
  { section: "7.3.3", title: "Control", page: 385, level: 3 },
  { section: "7.3.4", title: "Isolation", page: 386, level: 3 },
  { section: "7.3.5", title: "Overcurrent protection", page: 387, level: 3 },
  { section: "7.3.6", title: "Earthing", page: 388, level: 3 },
  { section: "7.3.7", title: "Connected electrical equipment", page: 388, level: 3 },
  { section: "7.3.8", title: "Connection to electrical installation", page: 389, level: 3 },
  { section: "7.4", title: "PROTECTION BY ELECTRICAL SEPARATION (ISOLATED SUPPLY)", page: 397, level: 2 },
  { section: "7.4.1", title: "General", page: 397, level: 3 },
  { section: "7.4.2", title: "Source of supply", page: 397, level: 3 },
  { section: "7.4.3", title: "Arrangement of circuits", page: 398, level: 3 },
  { section: "7.4.4", title: "Switching devices", page: 398, level: 3 },
  { section: "7.4.5", title: "Supply to single item of electrical equipment", page: 398, level: 3 },
  { section: "7.4.6", title: "Supply to multiple items of electrical equipment", page: 398, level: 3 },
  { section: "7.4.7", title: "Variable speed drive (VSD) EMI filters", page: 399, level: 3 },
  { section: "7.4.8", title: "Testing", page: 399, level: 3 },
  { section: "7.5", title: "EXTRA-LOW VOLTAGE ELECTRICAL INSTALLATIONS", page: 402, level: 2 },
  { section: "7.5.1", title: "Scope", page: 402, level: 3 },
  { section: "7.5.2", title: "Application", page: 402, level: 3 },
  { section: "7.5.3", title: "Sources of supply to SELV and PELV systems", page: 402, level: 3 },
  { section: "7.5.4", title: "Separation requirements for SELV and PELV circuits", page: 403, level: 3 },
  { section: "7.5.5", title: "Arrangement of SELV circuits", page: 403, level: 3 },
  { section: "7.5.6", title: "Arrangement of PELV circuits", page: 404, level: 3 },
  { section: "7.5.7", title: "Voltage drop in conductors", page: 404, level: 3 },
  { section: "7.5.8", title: "Control of an electrical installation", page: 405, level: 3 },
  { section: "7.5.9", title: "Overcurrent protection", page: 405, level: 3 },
  { section: "7.5.10", title: "Connecting devices", page: 406, level: 3 },
  { section: "7.5.11", title: "Wiring systems", page: 406, level: 3 },
  { section: "7.5.12", title: "Testing", page: 406, level: 3 },
  { section: "7.6", title: "HIGH VOLTAGE ELECTRICAL INSTALLATIONS", page: 407, level: 2 },
  { section: "7.6.1", title: "Scope", page: 407, level: 3 },
  { section: "7.6.2", title: "Application", page: 407, level: 3 },
  { section: "7.6.3", title: "Issues relevant to high voltage installations", page: 408, level: 3 },
  { section: "7.7", title: "HAZARDOUS AREAS (EXPLOSIVE GAS OR COMBUSTIBLE DUSTS)", page: 408, level: 2 },
  { section: "7.7.1", title: "Scope", page: 408, level: 3 },
  { section: "7.7.2", title: "Classification of hazardous areas", page: 408, level: 3 },
  { section: "7.8", title: "STANDARDS FOR SPECIFIC ELECTRICAL INSTALLATIONS", page: 409, level: 2 },
  { section: "7.8.1", title: "Scope", page: 409, level: 3 },
  { section: "7.8.2", title: "Standards containing requirements that are additional to, replace, or modify the general requirements of this Standard", page: 410, level: 3 },
  { section: "7.8.3", title: "Standards containing guidance", page: 412, level: 3 },
  { section: "7.9", title: "SUPPLIES FOR ELECTRIC VEHICLES (NZ ONLY)", page: 413, level: 2 },
  { section: "7.9.1", title: "Scope", page: 413, level: 3 },
  { section: "7.9.2", title: "Supply (NZ only)", page: 413, level: 3 },
  { section: "7.9.3", title: "Domestic electrical installations (NZ only)", page: 414, level: 3 },
  { section: "7.9.4", title: "Other electrical installations (NZ only)", page: 415, level: 3 },

  // SECTION 8
  { section: "8", title: "VERIFICATION", page: 416, level: 1 },
  { section: "8.1", title: "GENERAL", page: 416, level: 2 },
  { section: "8.1.1", title: "Application", page: 416, level: 3 },
  { section: "8.1.2", title: "General requirements", page: 416, level: 3 },
  { section: "8.1.3", title: "Periodic inspection and testing", page: 416, level: 3 },
  { section: "8.2", title: "VISUAL INSPECTION", page: 417, level: 2 },
  { section: "8.2.1", title: "General", page: 417, level: 3 },
  { section: "8.2.2", title: "Checklist", page: 417, level: 3 },
  { section: "8.3", title: "TESTING", page: 419, level: 2 },
  { section: "8.3.1", title: "General", page: 419, level: 3 },
  { section: "8.3.2", title: "Test methods", page: 419, level: 3 },
  { section: "8.3.3", title: "Mandatory tests", page: 420, level: 3 },
  { section: "8.3.4", title: "Sequence of tests", page: 420, level: 3 },
  { section: "8.3.5", title: "Continuity of the earthing system", page: 421, level: 3 },
  { section: "8.3.6", title: "Insulation resistance", page: 422, level: 3 },
  { section: "8.3.7", title: "Polarity and correct circuit connections", page: 423, level: 3 },
  { section: "8.3.8", title: "'Text deleted'", page: 424, level: 3 },
  { section: "8.3.9", title: "Verification of earth fault-loop impedance (EFLI)", page: 425, level: 3 },
  { section: "8.3.10", title: "Operation of RCDs", page: 428, level: 3 },
  { section: "8.4", title: "VERIFICATION RECORDS", page: 429, level: 2 },

  // APPENDICES
  { section: "B", title: "CIRCUIT PROTECTION GUIDE", page: 439, level: 1 },
  { section: "B1", title: "SCOPE", page: 439, level: 2 },
  { section: "B2", title: "CIRCUIT ARRANGEMENTS", page: 439, level: 2 },
  { section: "B3", title: "PROTECTION AGAINST OVERCURRENT", page: 441, level: 2 },
  { section: "B3.1", title: "General", page: 441, level: 3 },
  { section: "B3.2", title: "Coordination between conductors and overload protective devices", page: 441, level: 3 },
  { section: "B3.2.1", title: "General", page: 441, level: 4 },
  { section: "B3.2.2", title: "Application", page: 443, level: 4 },
  { section: "B3.2.2.1", title: "General", page: 443, level: 5 },
  { section: "B3.2.2.2", title: "Protection by circuit-breakers", page: 443, level: 5 },
  { section: "B3.2.2.3", title: "Protection by fuses", page: 443, level: 5 },
  { section: "B4", title: "PROTECTION BY AUTOMATIC DISCONNECTION OF SUPPLY", page: 443, level: 2 },
  { section: "B4.1", title: "Application", page: 443, level: 3 },
  { section: "B4.2", title: "Principle", page: 443, level: 3 },
  { section: "B4.3", title: "Disconnection times", page: 444, level: 3 },
  { section: "B4.4", title: "The earth fault-loop", page: 447, level: 3 },
  { section: "B4.5", title: "Calculation of earth fault-loop impedance", page: 449, level: 3 },
  { section: "B4.6", title: "Earth fault-loop impedance measurement", page: 450, level: 3 },
  { section: "B5", title: "MAXIMUM CIRCUIT LENGTHS", page: 450, level: 2 },
  { section: "B5.1", title: "General", page: 450, level: 3 },
  { section: "B5.2", title: "Calculation of maximum length of circuit", page: 450, level: 3 },
  { section: "B5.2.1", title: "Determination of Zint", page: 450, level: 4 },
  { section: "B5.2.2", title: "Calculation method", page: 451, level: 4 },
  { section: "B5.2.3", title: "Guidance tables", page: 452, level: 4 },
  { section: "B5.2.4", title: "Text deleted", page: 452, level: 4 },
  { section: "B5.2.5", title: "Guidance table", page: 453, level: 4 },
  { section: "Table B1", title: "MAXIMUM ROUTE LENGTHS FOR DIFFERENT SIZES OF CONDUCTORS AND PROTECTIVE DEVICES", page: 452, level: 3, keywords: "route length, cable length, earth fault loop, EFLI, circuit breaker type B C D, fuse" },
  { section: "Table B2", title: "COMPARISON OF CIRCUIT ROUTE LENGTH BASED ON LOOP IMPEDANCE AND VARIOUS VOLTAGE DROPS", page: 454, level: 3, keywords: "voltage drop 5% 4% 3% 2.5% 1%, loop impedance, distributed circuit" },

  // APPENDIX C - CIRCUIT ARRANGEMENTS (Pages 456-490)
  { section: "C", title: "CIRCUIT ARRANGEMENTS", page: 456, level: 1 },
  { section: "C1", title: "SCOPE", page: 456, level: 2 },
  { section: "C2", title: "MAXIMUM DEMAND", page: 456, level: 2 },
  { section: "C2.1", title: "After diversity maximum demand", page: 456, level: 3 },
  { section: "C2.2", title: "Calculation of maximum demand in consumer mains and submains", page: 457, level: 3 },
  { section: "C2.3", title: "Domestic installations", page: 457, level: 3 },
  { section: "C2.3.1", title: "Method", page: 457, level: 4 },
  { section: "C2.3.2", title: "Examples of calculation", page: 462, level: 4 },
  { section: "C2.3.2.1", title: "Example 1", page: 462, level: 5 },
  { section: "C2.3.2.2", title: "Example 2", page: 463, level: 5 },
  { section: "C2.3.2.3", title: "Example 3", page: 464, level: 5 },
  { section: "C2.4", title: "Non-domestic installations", page: 466, level: 3 },
  { section: "C2.4.1", title: "Method", page: 466, level: 4 },
  { section: "C2.4.2", title: "Examples of calculation", page: 469, level: 4 },
  { section: "C2.4.2.1", title: "Example 4", page: 469, level: 5 },
  { section: "C2.4.2.2", title: "Example 5", page: 470, level: 5 },
  { section: "C2.4.3", title: "Alternative calculation method for commercial and light-industrial applications", page: 473, level: 4 },
  { section: "C2.4.3.1", title: "General", page: 473, level: 5 },
  { section: "C2.4.3.2", title: "Example", page: 473, level: 5 },
  { section: "C2.4.4", title: "Alternative method using switchboard diversity", page: 474, level: 4 },
  { section: "C2.5", title: "Maximum demand in final subcircuits", page: 475, level: 3 },
  { section: "C2.5.1", title: "General", page: 475, level: 4 },
  { section: "C2.5.2", title: "Welding machines", page: 475, level: 4 },
  { section: "C2.5.2.1", title: "Definitions", page: 475, level: 5 },
  { section: "C2.5.2.2", title: "Arc welding machines", page: 476, level: 5 },
  { section: "C2.5.2.3", title: "Resistance welding machines", page: 476, level: 5 },
  { section: "C2.5.3", title: "Domestic cooking appliances", page: 477, level: 4 },
  { section: "C2.5.4", title: "Interlocked equipment", page: 477, level: 4 },
  { section: "C3", title: "SIMPLIFIED PROTECTIVE DEVICE SELECTION", page: 477, level: 2 },
  { section: "C4", title: "SIMPLIFIED VOLTAGE DROP", page: 479, level: 2 },
  { section: "C4.1", title: "Background", page: 479, level: 3 },
  { section: "C4.2", title: "Examples", page: 481, level: 3 },
  { section: "C5", title: "NUMBER OF POINTS CONNECTED TO CIRCUITS", page: 482, level: 2 },
  { section: "C5.1", title: "Number of circuits", page: 482, level: 3 },
  { section: "C5.2", title: "Final subcircuits", page: 482, level: 3 },
  { section: "C6", title: "GUIDE TO MAXIMUM NUMBER OF CABLES INSTALLED IN CONDUITS", page: 486, level: 2 },
  { section: "C6.1", title: "General", page: 486, level: 3 },
  { section: "C6.2", title: "Basis of calculations", page: 486, level: 3 },
  { section: "C6.3", title: "Application notes", page: 486, level: 3 },
  { section: "Table C1", title: "MAXIMUM DEMAND—SINGLE AND MULTIPLE DOMESTIC ELECTRICAL INSTALLATIONS", page: 458, level: 3, keywords: "domestic maximum demand, lighting points, socket outlets, ranges, water heaters, communal services" },
  { section: "Table C2", title: "MAXIMUM DEMAND—NON-DOMESTIC ELECTRICAL INSTALLATIONS", page: 467, level: 3, keywords: "commercial, industrial, shops, offices, schools, factories" },
  { section: "Table C3", title: "MAXIMUM DEMAND—ENERGY DEMAND METHOD FOR NON-DOMESTIC INSTALLATIONS", page: 474, level: 3, keywords: "VA per square metre, offices, carparks, retail, warehouses" },
  { section: "Table C4", title: "UPSTREAM CIRCUIT LOADING AFTER DIVERSITY", page: 475, level: 3, keywords: "diversity factor, switchboard" },
  { section: "Table C5", title: "MAXIMUM DEMAND—DOMESTIC COOKING APPLIANCES", page: 477, level: 3, keywords: "cooking appliance, range, oven, hotplate" },
  { section: "Table C6", title: "SIMPLIFIED PROTECTIVE DEVICE SELECTION FOR CABLES 1mm² TO 25mm² SINGLE-PHASE", page: 478, level: 3, keywords: "cable selection, circuit breaker, single phase, thermal insulation" },
  { section: "Table C7", title: "SIMPLIFIED PROTECTIVE DEVICE SELECTION FOR CABLES 1mm² TO 25mm² THREE-PHASE", page: 479, level: 3, keywords: "cable selection, circuit breaker, three phase" },
  { section: "Table C8", title: "VOLTAGE DROP—SIMPLIFIED METHOD", page: 481, level: 3, keywords: "voltage drop, Am per %Vd" },
  { section: "Table C9", title: "GUIDANCE ON THE LOADING OF POINTS PER FINAL SUBCIRCUIT", page: 483, level: 3, keywords: "points per circuit, socket outlets, lighting points" },
  { section: "Table C10", title: "GUIDE TO MAXIMUM NUMBER OF SINGLE-CORE SHEATHED CABLES IN CONDUIT", page: 488, level: 3, keywords: "conduit fill, single core" },
  { section: "Table C11", title: "GUIDE TO MAXIMUM NUMBER OF TWO-CORE AND EARTH CABLES IN CONDUIT", page: 489, level: 3, keywords: "conduit fill, TPS" },
  { section: "Table C12", title: "GUIDE TO MAXIMUM NUMBER OF FOUR-CORE AND EARTH CABLES IN CONDUIT", page: 490, level: 3, keywords: "conduit fill, three phase cable" },

  // APPENDIX D - MINIMUM SIZES OF POSTS, POLES AND STRUTS (Pages 491-512)
  { section: "D", title: "MINIMUM SIZES OF POSTS, POLES AND STRUTS FOR AERIAL LINE CONDUCTORS", page: 491, level: 1 },
  { section: "D1", title: "APPLICATION", page: 491, level: 2 },
  { section: "D1.1", title: "General", page: 491, level: 3 },
  { section: "D1.2", title: "Using the tables in this Appendix", page: 491, level: 3 },
  { section: "D2", title: "GENERAL REQUIREMENTS FOR POSTS AND POLES", page: 492, level: 2 },
  { section: "D2.1", title: "Sinking of posts/poles in ground", page: 492, level: 3 },
  { section: "D2.2", title: "Timber posts/poles", page: 493, level: 3 },
  { section: "D2.3", title: "Steel-pipe posts/poles", page: 493, level: 3 },
  { section: "D3", title: "ATTACHMENTS TO BUILDINGS OR STRUCTURES", page: 494, level: 2 },
  { section: "D3.1", title: "Responsibility for design", page: 494, level: 3 },
  { section: "D3.2", title: "Horizontal and vertical struts", page: 494, level: 3 },
  { section: "D4", title: "EXAMPLE USING THE TABLES TO DETERMINE POLE/POST OR STRUT SIZE", page: 495, level: 2 },
  { section: "D4.1", title: "Problem", page: 495, level: 3 },
  { section: "D4.2", title: "Solution", page: 495, level: 3 },
  { section: "D4.2.1", title: "Determine the minimum length of pole/post", page: 495, level: 4 },
  { section: "D4.2.2", title: "Select the minimum pole/post strength and size", page: 496, level: 4 },
  // All the D tables with proper keywords
  { section: "Table D1", title: "SINKING OF POSTS/POLES IN GROUND", page: 498, level: 3, keywords: "pole depth, poor soil, medium soil, good soil" },
  { section: "Table D2", title: "FORCE EXERTED BY AERIAL LINE CONDUCTORS", page: 499, level: 3, keywords: "aerial tension, conductor weight, sag, span" },
  { section: "Table D1", title: "SINKING OF POSTS/POLES IN GROUND", page: 498, level: 3, keywords: "pole depth, post depth, poor soil, medium soil, good soil, free length, conductor support", parent_section: "D" },
  { section: "Table D2", title: "FORCE EXERTED BY AERIAL LINE CONDUCTORS", page: 499, level: 3, keywords: "aerial line force, conductor weight, aerial span, minimum sag, maximum sag, aerial tension, breaking tension, pole strength, S rating, copper conductors, aluminium conductors", parent_section: "D" },
  { section: "Table D3", title: "SQUARE HARDWOOD POST (100 MPa TIMBER TO AS 2209) STRENGTH RATINGS", page: 500, level: 3, keywords: "hardwood post, timber post, square post, 100mm 125mm 150mm 175mm 200mm, strength rating, direct in ground, concrete in ground", parent_section: "D" },
  { section: "Table D4", title: "SQUARE HARDWOOD STRUTS (100 MPa TIMBER TO AS 2209) STRENGTH RATINGS", page: 501, level: 3, keywords: "hardwood struts, timber struts, square struts, 100mm 125mm 150mm 175mm 200mm", parent_section: "D" },
  { section: "Table D5", title: "ROUND HARDWOOD POLE (100 MPa TIMBER TO AS 2209) STRENGTH RATINGS—HEIGHT REDUCED FROM BASE", page: 501, level: 3, keywords: "round pole, hardwood pole, timber pole, 2kN 4kN 6kN, 8m 9.5m pole, height reduced from base", parent_section: "D" },
  { section: "Table D6", title: "ROUND HARDWOOD POLE (100 MPa TIMBER TO AS 2209) STRENGTH RATINGS—HEIGHT REDUCED FROM TOP", page: 502, level: 3, keywords: "round pole, hardwood pole, timber pole, 2kN 4kN 6kN, 8m 9.5m pole, height reduced from top", parent_section: "D" },
  { section: "Table D7", title: "ANGLE IRON STRUTS GRADE 250 STRENGTH RATINGS", page: 503, level: 3, keywords: "angle iron, steel struts, grade 250, 25x25 30x30 40x40 45x45 50x50 55x55 65x65 75x75 90x90 100x100", parent_section: "D" },
  { section: "Table D8", title: "ANGLE IRON STRUTS GRADE 300 STRENGTH RATINGS", page: 504, level: 3, keywords: "angle iron, steel struts, grade 300, 125x125 150x150 200x200", parent_section: "D" },
  { section: "Table D9", title: "FABRICATED RIVERTON OCTAGONAL STEEL POLE STRENGTH RATINGS", page: 504, level: 3, keywords: "octagonal pole, steel pole, riverton pole, fabricated pole", parent_section: "D" },
  { section: "Table D10", title: "GRADE 250 STEEL-PIPE (DIAMETER × THICKNESS, mm) STRENGTH RATINGS", page: 505, level: 3, keywords: "steel pipe, grade 250, pipe pole, 34mm 42mm 48mm 60mm 76mm 89mm 102mm 114mm 140mm 165mm diameter", parent_section: "D" },
  { section: "Table D11", title: "GRADE 350 STEEL-PIPE (DIAMETER × THICKNESS, mm) STRENGTH RATINGS", page: 506, level: 3, keywords: "steel pipe, grade 350, pipe pole, 34mm 42mm 48mm 60mm 76mm 89mm 102mm 114mm 140mm 165mm 168mm 219mm diameter", parent_section: "D" },
  { section: "Table D12(A)", title: "GRADE 350 STEEL SQUARE SECTION (WIDTH × THICKNESS, mm) STRENGTH RATINGS", page: 507, level: 3, keywords: "square hollow section, SHS, grade 350, 30mm 35mm 40mm 50mm 65mm square", parent_section: "D" },
  { section: "Table D12(B)", title: "GRADE 350 STEEL SQUARE SECTION (WIDTH × THICKNESS, mm) STRENGTH RATINGS (CONTINUED)", page: 508, level: 3, keywords: "square hollow section, SHS, grade 350, 75mm 89mm 100mm 125mm 150mm 200mm square", parent_section: "D" },
  { section: "Table D13(A)", title: "GRADE 450 STEEL SQUARE SECTION (WIDTH × THICKNESS, mm) STRENGTH RATINGS", page: 510, level: 3, keywords: "square hollow section, SHS, grade 450, 30mm 35mm 40mm 50mm square", parent_section: "D" },
  { section: "Table D13(B)", title: "GRADE 450 STEEL SQUARE SECTION (WIDTH × THICKNESS, mm) STRENGTH RATINGS (CONTINUED)", page: 511, level: 3, keywords: "square hollow section, SHS, grade 450, 50mm 65mm 75mm 100mm square", parent_section: "D" },

  // APPENDIX E - ELECTRICAL INSTALLATION REQUIREMENTS IN NATIONAL CONSTRUCTION CODES (Pages 513-520)
  { section: "E", title: "ELECTRICAL INSTALLATION REQUIREMENTS IN NATIONAL CONSTRUCTION CODES", page: 513, level: 1 },
  { section: "E1", title: "SCOPE", page: 513, level: 2 },
  { section: "E2", title: "AUSTRALIA", page: 513, level: 2 },
  { section: "E2.1", title: "General", page: 513, level: 3 },
  { section: "E2.2", title: "Principles of classification", page: 514, level: 3 },
  { section: "E2.2.1", title: "General", page: 514, level: 4 },
  { section: "E2.2.2", title: "Classifications", page: 514, level: 4 },
  { section: "E2.2.3", title: "Multiple classification", page: 516, level: 4 },
  { section: "E2.2.4", title: "Parts with more than one classification", page: 516, level: 4 },
  { section: "E2.3", title: "Provisions in the NCC", page: 516, level: 3 },
  { section: "E2.3.1", title: "General", page: 516, level: 4 },
  { section: "E2.3.2", title: "Fire safety", page: 517, level: 4 },
  { section: "E2.3.3", title: "Safety (other than fire safety) health and amenity", page: 517, level: 4 },
  { section: "E2.3.4", title: "Sustainability—Energy efficiency", page: 518, level: 4 },
  { section: "E3", title: "NEW ZEALAND", page: 518, level: 2 },
  { section: "E3.1", title: "General", page: 518, level: 3 },
  { section: "E3.2", title: "Extent of electrical installations in the NZBC", page: 519, level: 3 },
  { section: "E3.3", title: "Building consents", page: 520, level: 3 },

  // APPENDIX F - SURGE PROTECTIVE DEVICES (Pages 521-526)
  { section: "F", title: "SURGE PROTECTIVE DEVICES", page: 521, level: 1 },
  { section: "F1", title: "SURGE PROTECTIVE DEVICES (SPDs)", page: 521, level: 2 },
  { section: "F1.1", title: "General", page: 521, level: 3 },
  { section: "F1.2", title: "Selection and installation of SPDs", page: 521, level: 3 },
  { section: "F1.2.1", title: "Location", page: 521, level: 4 },
  { section: "F1.2.2", title: "Installation", page: 522, level: 4 },
  { section: "F1.2.3", title: "Selection of surge protection devices (SPDs)", page: 524, level: 4 },
  { section: "F1.2.4", title: "Overcurrent protective devices", page: 524, level: 4 },
  { section: "F1.2.5", title: "Connecting conductors", page: 524, level: 4 },
  { section: "F2", title: "SURGE PROTECTIVE EARTHING AND BONDING", page: 525, level: 2 },

  // APPENDIX G - DEGREES OF PROTECTION OF ENCLOSED EQUIPMENT (Pages 527-531)
  { section: "G", title: "DEGREES OF PROTECTION OF ENCLOSED EQUIPMENT", page: 527, level: 1 },
  { section: "Table H1", title: "DEGREE OF PROTECTION INDICATED BY THE FIRST CHARACTERISTIC NUMERAL", page: 533, level: 3, keywords: "IP rating, first numeral, solid objects" },
  { section: "Table H2", title: "DEGREE OF PROTECTION INDICATED BY THE SECOND CHARACTERISTIC NUMERAL", page: 534, level: 3, keywords: "IP rating, second numeral, water ingress" },
  
  // APPENDIX H - WS CLASSIFICATION OF WIRING SYSTEMS (Pages 532-539)
  { section: "H", title: "WS CLASSIFICATION OF WIRING SYSTEMS", page: 532, level: 1 },
  { section: "H1", title: "GENERAL", page: 532, level: 2 },
  { section: "H1.1", title: "Classification", page: 532, level: 3 },
  { section: "H1.2", title: "Designation", page: 532, level: 3 },
  { section: "H1.2.1", title: "General", page: 532, level: 4 },
  { section: "H1.2.2", title: "Basic designation", page: 532, level: 4 },
  { section: "H1.2.3", title: "Single characteristic numeral designation", page: 533, level: 4 },
  { section: "H1.3", title: "First characteristic numeral", page: 533, level: 3 },
  { section: "H1.4", title: "Second characteristic numeral", page: 533, level: 3 },
  { section: "H1.5", title: "Supplementary letter W", page: 534, level: 3 },
  { section: "H1.6", title: "Supply and installation", page: 534, level: 3 },
  { section: "H1.6.1", title: "Components", page: 534, level: 4 },
  { section: "H1.6.2", title: "Instructions", page: 534, level: 4 },
  { section: "H2", title: "PARTICULAR WIRING SYSTEM APPLICATIONS", page: 534, level: 2 },
  { section: "H2.1", title: "Building Code", page: 534, level: 3 },
  { section: "H2.2", title: "Equipment installation Standards", page: 535, level: 3 },
  { section: "H3", title: "FIRE-PROTECTED WIRING SYSTEMS", page: 536, level: 2 },
  { section: "H4", title: "MECHANICALLY PROTECTED WIRING SYSTEMS", page: 536, level: 2 },
  { section: "H4.1", title: "General", page: 536, level: 3 },
  { section: "H4.2", title: "Application of wiring systems", page: 536, level: 3 },
  { section: "H4.3", title: "Unenclosed wiring systems", page: 537, level: 3 },
  { section: "H4.4", title: "Enclosed wiring systems", page: 537, level: 3 },
  { section: "H5", title: "GUIDE TO MECHANICAL PROTECTION CLASSIFICATION", page: 538, level: 2 },
  { section: "H5.1", title: "General", page: 538, level: 3 },
  { section: "H5.2", title: "WSX1 mechanical protection systems", page: 538, level: 3 },
  { section: "H5.3", title: "WSX2 mechanical protection systems", page: 538, level: 3 },
  { section: "H5.4", title: "WSX3 mechanical protection systems", page: 539, level: 3 },
  { section: "Table H1", title: "DEGREE OF PROTECTION INDICATED BY THE FIRST CHARACTERISTIC NUMERAL", page: 533, level: 3, keywords: "WS rating, fire protection, circuit integrity, time duration" },
  { section: "Table H2", title: "DEGREE OF PROTECTION INDICATED BY THE SECOND CHARACTERISTIC NUMERAL", page: 534, level: 3, keywords: "mechanical damage, impact protection, light moderate heavy impact" },
  { section: "Figure H1", title: "WSX1 PROTECTION BY LOCATION", page: 538, level: 3 },

  // APPENDIX I - PROTECTIVE DEVICE RATINGS AND METRIC EQUIVALENT SIZES (Pages 540-542)
  { section: "I", title: "PROTECTIVE DEVICE RATINGS AND METRIC EQUIVALENT SIZES FOR IMPERIAL CABLES USED IN ALTERATIONS AND REPAIRS", page: 540, level: 1 },
  { section: "I1", title: "SCOPE", page: 540, level: 2 },
  { section: "I2", title: "PROTECTIVE DEVICE RATINGS", page: 540, level: 2 },
  { section: "I3", title: "METRIC EQUIVALENT SIZES FOR IMPERIAL CONDUCTORS", page: 542, level: 2 },
  { section: "Table I1", title: "PROTECTIVE DEVICE RATINGS", page: 541, level: 3, keywords: "imperial cables, V75 V60 insulation, circuit breaker, fuse ratings, alterations repairs" },
  { section: "Table I2", title: "SIZES OF IMPERIAL AND METRIC CABLES FOR CONNECTION IN PARALLEL", page: 542, level: 3, keywords: "imperial to metric conversion, parallel cables, conductor sizes" },

  // APPENDIX J - SYMBOLS USED IN THIS STANDARD (Pages 543-544)
  { section: "J", title: "SYMBOLS USED IN THIS STANDARD", page: 543, level: 1 },
  { section: "Figure J1", title: "SYMBOLS USED IN THIS STANDARD", page: 544, level: 3 },

  // APPENDIX K - SWITCHBOARD REQUIREMENT SUMMARY (Pages 545-557)
  { section: "K", title: "SWITCHBOARD REQUIREMENT SUMMARY", page: 545, level: 1 },
  { section: "K1", title: "GENERAL", page: 545, level: 2 },
  { section: "K1.1", title: "Introduction", page: 545, level: 3 },
  { section: "K1.2", title: "Deemed to comply", page: 545, level: 3 },
  { section: "K2", title: "SWITCHBOARD STANDARDS", page: 545, level: 2 },
  { section: "K2.1", title: "General", page: 545, level: 3 },
  { section: "K2.2", title: "Withdrawal date of the AS/NZS 3439 series", page: 546, level: 3 },
  { section: "K2.3", title: "Testing", page: 546, level: 3 },
  { section: "K3", title: "APPLICATION OF THE AS/NZS 61439 SERIES", page: 546, level: 2 },
  { section: "K3.1", title: "General rules", page: 546, level: 3 },
  { section: "K3.2", title: "Power switchgear and controlgear (PSC)", page: 546, level: 3 },
  { section: "K3.3", title: "Distribution boards intended to be operated by ordinary persons (DBO)", page: 546, level: 3 },
  { section: "K4", title: "GUIDELINES FOR THE ASSESSMENT OF SWITCHBOARDS", page: 546, level: 2 },
  { section: "K4.1", title: "User template", page: 546, level: 3 },
  { section: "K4.2", title: "Items subject to agreement", page: 546, level: 3 },
  { section: "K4.3", title: "Design verification", page: 547, level: 3 },
  { section: "K5", title: "CORRESPONDING PROVISIONS OF THIS STANDARD AND THE AS/NZS 61439 SERIES", page: 547, level: 2 },
  { section: "K6", title: "PARTICULAR CLAUSES RELEVANT TO THIS STANDARD", page: 548, level: 2 },
  { section: "K6.1", title: "Degree of protection of ASSEMBLIES", page: 548, level: 3 },
  { section: "K6.2", title: "Form of internal separation", page: 548, level: 3 },
  { section: "K6.3", title: "Clearance", page: 551, level: 3 },
  { section: "K6.4", title: "Overvoltage category", page: 551, level: 3 },
  { section: "K6.5", title: "Creepage", page: 551, level: 3 },
  { section: "K6.6", title: "Earthing (protective earth circuit)", page: 551, level: 3 },
  { section: "K6.7", title: "Dielectric tests for protection against electric shock", page: 551, level: 3 },
  { section: "K6.8", title: "Current rating by testing and temperature limits", page: 551, level: 3 },
  { section: "K6.9", title: "Derivation of ratings for similar variants to AS/NZS 61439.1", page: 553, level: 3 },
  { section: "K6.10", title: "Verification assessment to AS/NZS 61439.1", page: 553, level: 3 },
  { section: "K7", title: "SHORT-CIRCUIT WITHSTAND STRENGTH", page: 553, level: 2 },
  { section: "K7.1", title: "General", page: 553, level: 3 },
  { section: "K7.2", title: "Ratings", page: 553, level: 3 },
  { section: "K7.2.1", title: "Short time withstand current rating (Icw)", page: 553, level: 4 },
  { section: "K7.2.2", title: "Backup (cascading)", page: 554, level: 4 },
  { section: "K7.3", title: "Short-circuit withstand strength by comparison to a reference design utilizing a check list", page: 554, level: 3 },
  { section: "K8", title: "MARKING", page: 554, level: 2 },
  { section: "K8.1", title: "PSC and DBO switchboards", page: 554, level: 3 },
  { section: "K8.2", title: "Additional marking for DBO", page: 554, level: 3 },
  { section: "K9", title: "OTHER RELEVANT CHARACTERISTICS TO BE DECLARED BY THE ASSEMBLY MANUFACTURER", page: 555, level: 2 },
  { section: "K10", title: "DEVICE SUBSTITUTION", page: 555, level: 2 },
  { section: "K10.1", title: "General", page: 555, level: 3 },
  { section: "K10.2", title: "Device substitution questions", page: 556, level: 3 },
  { section: "K11", title: "REPAIRS TO EXISTING SWITCHBOARDS", page: 556, level: 2 },
  { section: "K12", title: "ROUTINE VERIFICATION BY THE SWITCHBOARD MANUFACTURER", page: 557, level: 2 },
  { section: "Table K1", title: "CORRESPONDING PROVISIONS BETWEEN AS/NZS 3000 AND THE AS/NZS 61439 SERIES", page: 548, level: 3, keywords: "switchboard standards, AS/NZS 61439, clause correspondence" },
  { section: "Table K2", title: "MINIMUM REQUIREMENTS FOR INTERNAL SEPARATION", page: 550, level: 3, keywords: "form separation, form 1 2 3 4, busbars, functional units" },

  // APPENDIX L - DELETED (Page 558)
  { section: "L", title: "(Deleted)", page: 558, level: 1 },

  // APPENDIX M - REDUCING IMPACT OF POWER SUPPLY OUTAGES (Pages 559-560)
  { section: "M", title: "REDUCING THE IMPACT OF POWER SUPPLY OUTAGES—CONTINUITY OF SUPPLY FOR ACTIVE ASSISTED LIVING AND HOMECARE MEDICAL SITUATIONS", page: 559, level: 1 },
  { section: "M1", title: "GENERAL", page: 559, level: 2 },
  { section: "M1.1", title: "Scope", page: 559, level: 3 },
  { section: "M1.2", title: "Active assisted living", page: 559, level: 3 },
  { section: "M1.3", title: "Homecare medical", page: 559, level: 3 },
  { section: "M2", title: "ARRANGEMENTS", page: 559, level: 2 },

  // APPENDIX N - ELECTRICAL CONDUITS (Pages 561-564)
  { section: "N", title: "ELECTRICAL CONDUITS", page: 561, level: 1 },
  { section: "N1", title: "GENERAL", page: 561, level: 2 },
  { section: "N2", title: "MARKING OF AS/NZS 2053 SERIES AND AS/NZS 61386 SERIES CONDUITS", page: 561, level: 2 },
  { section: "N3", title: "CLASSIFICATIONS", page: 562, level: 2 },
  { section: "Table N1", title: "FIRST AND SECOND NUMERALS IN COMPARISON WITH DUTY RATINGS IN AS/NZS 2053 SERIES AND AS/NZS 61386 SERIES", page: 563, level: 3, keywords: "conduit duty ratings, VLD LD MD HD VHD, compression impact resistance" },
  { section: "Table N2", title: "THIRD AND FOURTH NUMERALS FOR TEMPERATURE RATINGS COMPARISON BETWEEN AS/NZS 2053 SERIES AND AS/NZS 61386 SERIES", page: 564, level: 3, keywords: "conduit temperature ratings, lower upper temperature range" },

  // APPENDIX O - INSTALLATION OF ARC FAULT DETECTION DEVICES (AFDDs) (Pages 565-567)
  { section: "O", title: "INSTALLATION OF ARC FAULT DETECTION DEVICES (AFDDs)", page: 565, level: 1 },
  { section: "O1", title: "GENERAL", page: 565, level: 2 },
  { section: "O2", title: "CHARACTERISTICS OF AFDDs", page: 566, level: 2 },
  { section: "O3", title: "GENERAL REQUIREMENTS FOR AFDDs", page: 567, level: 2 },
  { section: "O4", title: "LOCATION, SELECTION AND INSTALLATION OF AFDDs", page: 567, level: 2 },
  { section: "O4.1", title: "Location", page: 567, level: 3 },
  { section: "O4.2", title: "Selection of AFDDs", page: 567, level: 3 },
  { section: "O4.3", title: "Installation", page: 567, level: 3 },
  { section: "O4.4", title: "Overvoltage protection", page: 567, level: 3 },
  { section: "Figure O1", title: "TYPES OF ARC FAULT", page: 566, level: 3 },

  // APPENDIX P - GUIDANCE FOR INSTALLATION AND LOCATION OF ELECTRICAL VEHICLE SOCKET-OUTLETS AND CHARGING STATIONS (Pages 568-574)
  { section: "P", title: "GUIDANCE FOR INSTALLATION AND LOCATION OF ELECTRICAL VEHICLE SOCKET-OUTLETS AND CHARGING STATIONS", page: 568, level: 1 },
  { section: "P1", title: "SCOPE AND GENERAL", page: 568, level: 2 },
  { section: "P1.1", title: "Scope", page: 568, level: 3 },
  { section: "P1.2", title: "Applications", page: 568, level: 3 },
  { section: "P1.3", title: "Additional requirements and tests", page: 568, level: 3 },
  { section: "P1.4", title: "Exclusions", page: 569, level: 3 },
  { section: "P1.5", title: "Definitions", page: 569, level: 3 },
  { section: "P1.5.1", title: "Connecting point", page: 569, level: 4 },
  { section: "P1.5.2", title: "Mode 1 charging", page: 569, level: 4 },
  { section: "P1.5.3", title: "Mode 2 charging", page: 569, level: 4 },
  { section: "P1.5.4", title: "Mode 3 charging", page: 569, level: 4 },
  { section: "P1.5.5", title: "Mode 4 charging", page: 569, level: 4 },
  { section: "P1.5.6", title: "Demand factor", page: 569, level: 4 },
  { section: "P1.5.7", title: "Vehicle coupler", page: 570, level: 4 },
  { section: "P1.5.8", title: "Vehicle connector", page: 570, level: 4 },
  { section: "P1.5.9", title: "Vehicle inlet", page: 570, level: 4 },
  { section: "P2", title: "MAXIMUM DEMAND", page: 570, level: 2 },
  { section: "P3", title: "INSTALLATION", page: 570, level: 2 },
  { section: "P3.1", title: "General", page: 570, level: 3 },
  { section: "P3.2", title: "External Influences", page: 570, level: 3 },
  { section: "P3.2.1", title: "Water or high humidity", page: 570, level: 4 },
  { section: "P3.2.2", title: "Solid foreign bodies", page: 570, level: 4 },
  { section: "P3.2.3", title: "Mechanical damage", page: 570, level: 4 },
  { section: "P4", title: "DEVICES FOR PROTECTION AGAINST INDIRECT CONTACT BY AUTOMATIC DISCONNECTION OF SUPPLY", page: 571, level: 2 },
  { section: "P4.1", title: "RCDs", page: 571, level: 3 },
  { section: "P4.2", title: "Devices for protection against overcurrent", page: 571, level: 3 },
  { section: "P4.3", title: "Protective conductors", page: 571, level: 3 },
  { section: "P5", title: "OTHER EQUIPMENT", page: 571, level: 2 },
  { section: "P5.1", title: "Socket-outlets and vehicle connectors", page: 571, level: 3 },
  { section: "P5.2", title: "Ratings of vehicle couplers, socket-outlets and plugs", page: 572, level: 3 },
  { section: "P5.2.1", title: "Type 1 vehicle coupler", page: 572, level: 4 },
  { section: "P5.2.2", title: "Type 2 vehicle coupler, socket-outlet and plug", page: 572, level: 4 },
  { section: "P5.2.3", title: "Type 3 vehicle coupler", page: 572, level: 4 },
  { section: "P5.2.4", title: "Type 3 socket-outlet and plug", page: 572, level: 4 },
  { section: "P5.3", title: "Permitted socket-outlets or vehicle connectors", page: 572, level: 3 },
  { section: "P5.4", title: "Types of connection", page: 572, level: 3 },
  { section: "P5.4.1", title: "Case A connection", page: 572, level: 4 },
  { section: "P5.4.2", title: "Case B connection", page: 573, level: 4 },
  { section: "P5.4.3", title: "Case C connection", page: 573, level: 4 },
  { section: "P6", title: "CHARGING STATIONS AND CABLES", page: 574, level: 2 },
  { section: "P7", title: "PERIODIC VERIFICATION", page: 574, level: 2 },
  { section: "Figure P1", title: "CASE A CONNECTION", page: 573, level: 3 },
  { section: "Figure P2", title: "CASE B CONNECTION", page: 573, level: 3 },
  { section: "Figure P3", title: "CASE C CONNECTION", page: 573, level: 3 },

  // APPENDIX Q - D.C. CIRCUIT PROTECTION APPLICATION GUIDE (Pages 575-577)
  { section: "Q", title: "D.C. CIRCUIT PROTECTION APPLICATION GUIDE", page: 575, level: 1 },
  { section: "Q1", title: "SCOPE", page: 575, level: 2 },
  { section: "Q2", title: "GENERAL", page: 575, level: 2 },
  { section: "Q3", title: "ARC SUPPRESSION", page: 575, level: 2 },
  { section: "Q4", title: "SWITCHGEAR TYPES", page: 575, level: 2 },
  { section: "Q4.1", title: "Polarized", page: 575, level: 3 },
  { section: "Q4.2", title: "Non-polarized type", page: 576, level: 3 },
  { section: "Q5", title: "D.C. RATINGS", page: 576, level: 2 },
  { section: "Q5.1", title: "General", page: 576, level: 3 },
  { section: "Q5.2", title: "Earthed D.C. supply", page: 576, level: 3 },
  { section: "Q6", title: "PROVISION OF ISOLATION AND OVERCURRENT PROTECTION", page: 576, level: 2 },
  { section: "Q7", title: "SWITCHBOARD LOCATIONS", page: 576, level: 2 },
  { section: "Q8", title: "FINAL SUBCIRCUIT WIRING AND FITTINGS", page: 577, level: 2 },
  { section: "Q9", title: "INVERTERS", page: 577, level: 2 }
]
  

// --- helpers ---
const norm = s => (s||"")
  .toLowerCase()
  .replace(/[^a-z0-9\.\-\s]/g, " ")
  .replace(/\s+/g, " ")
  .trim()

export const buildTocIndex = (toc = AS_NZS_3000_TOC) => {
  const byId = new Map()
  const byTitle = new Map()
  const all = []
  for (const item of toc) {
    const id = String(item.section)
    const title = String(item.title)
    const page = Number(item.page)
    const level = Number(item.level || 0)
    const aliases = item.aliases || []

    const entry = { id, title, page, level, aliases }
    byId.set(id, entry)

    const titleKey = norm(title)
    if (!byTitle.has(titleKey)) byTitle.set(titleKey, [])
    byTitle.get(titleKey).push(entry)

    for (const a of aliases) {
      const k = norm(a)
      if (!byTitle.has(k)) byTitle.set(k, [])
      byTitle.get(k).push(entry)
    }
    all.push(entry)
  }
  return { byId, byTitle, all }
}

export const TOC_INDEX = buildTocIndex(AS_NZS_3000_TOC)

export const fuzzyTitleScore = (a, b) => {
  const A = new Set(norm(a).split(" "))
  const B = new Set(norm(b).split(" "))
  if (!A.size || !B.size) return 0
  let inter = 0
  for (const w of A) if (B.has(w)) inter++
  return inter / Math.max(A.size, B.size)
}

export const keywordOverlap = (query, title) => {
  const stop = new Set(["the","a","an","of","and","or","to","for","in","on","near","with","by","is","are","be","can","how","what"])
  const q = norm(query).split(" ").filter(w => w && !stop.has(w))
  const t = new Set(norm(title).split(" "))
  if (!q.length || !t.size) return 0
  let hit = 0
  for (const w of q) if (t.has(w)) hit++
  return hit / Math.min(q.length, t.size)
}

// Optional: if you still need parent sections somewhere
export const getParentSection = (id) => {
  const parts = String(id).split('.')
  if (parts.length <= 1) return null
  parts.pop()
  return parts.join('.')
}